# Generated by Django 4.0 on 2021-12-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='FAQ Title')),
                ('description', models.TextField(verbose_name='FAQ Description')),
            ],
        ),
    ]
