# Generated by Django 4.0 on 2021-12-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Client Name')),
                ('designation', models.CharField(max_length=50, verbose_name='Client Designation')),
                ('description', models.TextField(verbose_name='Clent Feedback')),
                ('image', models.ImageField(blank=True, upload_to='client', verbose_name='Client Image')),
            ],
        ),
    ]
