# Generated by Django 4.0 on 2021-12-23 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.TextField(blank=True, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, upload_to='service/', verbose_name='Service Image')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_service', to='department.department', verbose_name='Department')),
            ],
        ),
    ]
